require("config.options")
require("config.dependencies")
require("config.treesitter")
require("config.folding")
require("config.statuscolumn")
require("config.formatting")
require("config.keymaps")
require("config.copilot")
